<?php

// Load Field module hooks.
module_load_include('php', 'bibdk_cart', 'BibdkCart');
module_load_include('php', 'bibdk_cart', 'BibdkCartElement');
module_load_include('inc', 'bibdk_cart', 'bibdk_cart.field');
module_load_include('inc', 'bibdk_cart', 'bibdk_cart.webservice');

/**
 * Implements hook_menu().
 */
function bibdk_cart_menu() {
  $items['cart/ajax'] = array(
    'page callback' => 'bibdk_cart_add_to_cart',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'bibdk_cart.ajax.inc',
  );
  $items['cart/ajax/deleteitems'] = array(
    'page callback' => 'bibdk_cart_delete_selected',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'bibdk_cart.ajax.inc',
  );
  $items['user/cart'] = array(
    'title' => t('Cart'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bibdk_cart_view_form'),
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
    //'file' => 'bibdk_cart.ajax.inc',
  );
  return $items;
}

/**
 * Implements hook_theme().
 *
 * @return array
 */
function bibdk_cart_theme() {
  return array(
    'bibdk_cart_button' => array(
      'variables' => array('add_to_cart' => ''),
      'template' => 'theme/bibdk-cart-button',
    ),
    'bibdk_cart_view_primary_actions' => array(
      'variables' => array(),
      'template' => 'theme/bibdk-cart-view-primary-actions'
    ),
    'bibdk_cart_view_secondary_actions' => array(
      'variables' => array('actions' => array()),
      'template' => 'theme/bibdk-cart-view-secondary-actions'
    ),
    'bibdk_cart_button_subwork' => array(
      'variables' => array('add_to_cart' => ''),
      'template' => 'theme/bibdk-cart-button-subwork',
    ),
    'bibdk_cart_manifestation' => array(
      'template' => 'theme/bibdk-cart-manifestation',
      'variables' => array('fields' => array(), 'view_mode' => 'cart', 'id' => 0, 'pid' => '', 'title' => '', 'author' => '', 'type' => '', 'cart_btn' => '', 'several_editions' => ''),
      'render_element' => 'elements'
    ),
  );
}


/**
 * Implememts hook_user_profile_tabs (
 *
 * @see ding_user.module)
 * */
function bibdk_cart_user_profile2_tabs() {
  $ret = new stdClass();
  $ret->label = t('cart');
  $ret->form = 'bibdk_cart_get_form';
  $ret->type = 'bibdk_cart_list';
  return $ret;
}


/**
 * List view of cart
 *
 * @param $form
 * @param $form_state
 * @return array
 */

function bibdk_cart_view_form($form, &$form_state) {
  global $user;
  if ($user->uid) {
    drupal_goto('user/' . $user->uid . '/edit/bibdk_cart_list');
  }
  $cart = bibdk_cart_get_form($form, $form_state);
  $form['cart'] = $cart;
  return $form;
}

/**
 * Render cart view
 *
 * @param $form
 * @param $form_state
 * @return array
 */
function bibdk_cart_get_form($form, &$form_state) {
  $cart = BibdkCart::getAll();
  if (empty($cart)) {
    return array();
  }

  bibdk_cart_set_manifestations($cart);

  $items = array();
  foreach ($cart as $delta => $element) {
    $item = bibdk_cart_manifestation_view($element->getManifestation(), $element->getElementArray());
    $items[$delta]['manifestation'] = drupal_render($item);
    $items[$delta]['status'] = implode(', ', $element->getStatus());
/*
    if (isset($item['#fields']['bibdk_mani_reservation_button'][0]['#markup'])) {
      $items[$delta]['actions'] = $item['#fields']['bibdk_mani_reservation_button'][0]['#markup'];
    }
    else if (isset($item['#fields']['bibdk_reservation_info'][0]['#markup'])) {
      $items[$delta]['actions'] = $item['#fields']['bibdk_reservation_info'][0]['#markup'];
    }
    else {
      $items[$delta]['actions'] = "";
    }
*/
    $items[$delta]['actions'] = isset($item['action']) ? $item['action'] : '';
  }

  $form = bibdk_cart_get_priamry_actions($form);

  $form = bibdk_cart_get_secondary_actions($form);

  $header = array(
    'manifestation' => t('bibdk_cart_header', array(), array('context' => 'bibdk_cart')),
    'status' => t('bibdk_cart_status', array(), array('context' => 'bibdk_cart')),
    'actions' => t('bibdk_cart_actions', array(), array('context' => 'bibdk_cart')),
  );

  $form = _bibdk_cart_get_cart_table($header, $items, $form);

  return $form;
}

/**
 * @param array $form
 * @return array $form
 */
function bibdk_cart_get_priamry_actions($form) {
  $form['cart_table_priamry_actions'] = array(
    '#markup' => theme('bibdk_cart_view_primary_actions', array()),
    '#attached' => array(
      'js' => array(
        drupal_get_path('module', 'bibdk_cart') . '/js/bibdk_cart_view_primary_actions.js',
      ),
    ),
    '#attributes' => array(
      'class' => array(),
    ),
  );

  return $form;
}

/**
 * Invokes hook_cart_actions() in order to retrieve actions that should be included in the cart view
 *
 * @param array $form
 * @return array $form
 */
function bibdk_cart_get_secondary_actions($form) {
  $actions = array();
  $actions = module_invoke_all('cart_actions', $actions);

  if (!empty($actions)) {
    uasort($actions, 'element_sort');

    $actions_wrapper = array(
      '#type' => 'container',
      '#attributes' => array(
        'class' => array('cart-view-secondary-actions'),
      ),
    );

    $actions_wrapper['actions'] = $actions;
    $form['cart_table_secondary_actions'] = $actions_wrapper;
  }

  return $form;
}

/**
 * @param array $header
 * @param array $items
 * @param array $form
 * @return array $form
 */
function _bibdk_cart_get_cart_table($header, $items, $form) {
  $form['cart_table'] = array(
    '#type' => 'tableselect',
    '#header' => $header,
    '#options' => $items,
    '#empty' => t('no_items_in_cart_yet', array(), array('context' => 'bibdk_cart')),
    '#js_select' => FALSE,
    '#sticky' => FALSE,
    '#multiple' => TRUE,
    '#attributes' => array(
      'class' => array(
        'table',
        'element-wrapper',
        'cart-item-checkbox',
      ),
    ),
  );
  return $form;
}

/** Populate the cart with manifestations
 *
 * @param $cart
 */
function bibdk_cart_set_manifestations(&$cart) {
  foreach ($cart as $element) {
    $ids[] = $element->getElementId();
  }
  $manifestations = bibdk_cart_get_manifestations($ids);
  foreach ($cart as $element) {
    $manifestation = $manifestations[$element->getElementId()];
    $manifestation->ding_entity_id = $manifestation->id = $element->getElement();
    $element->setManifestation($manifestation);
  }
}

/**
 * Get manifestations
 *
 * @param $pids array
 * @return array manifestations
 */
function bibdk_cart_get_manifestations($pids) {
  /**
   * ting_openformat_get_manifestations returns a bibdkWork as an array and all
   * the manifestations are saved in the manifestations variable.
   * TODO :ting_openformat should have a method to return an array of manifestations
   */
  $works = ting_openformat_get_manifestations($pids);
  $work = reset($works);
  return (isset($work->manifestations)) ? $work->manifestations : NULL;
}

/**
 * Render cart view of single manifestation
 *
 * @param manifestation $manifestation
 * @param $pids
 * @return array
 */
function bibdk_cart_manifestation_view($manifestation, $pids) {
  $view = ting_openformat_manifestation_view($manifestation, 'cart');

  if (isset($view['#fields']['bibdk_mani_reservation_button'])) {
    $view['action'] = $view['#fields']['bibdk_mani_reservation_button'][0]['#markup'];
    unset($view['#fields']['bibdk_mani_reservation_button']);
  }

  _bibdk_cart_manifestation_view_strip_links($view);

  $view['#theme'] = 'bibdk_cart_manifestation';
  $view += array(
    '#pid' => drupal_strtolower(preg_replace('/[^a-zA-Z0-9-]+/', '-', $manifestation->id)),
    '#several_editions' => (!empty($pids) && count($pids) > 1) ? t('all_editions', array(), array('context' => 'bibdk_cart')) : '',
    '#fields' => $view['#fields'],
  );
  return $view;
}

/**
 * Implements hook_entity_info_alter().
 */
function bibdk_cart_entity_info_alter(&$entity_info) {
  $entity_info['bibdkManifestation']['view modes']['cart'] = array(
    'label' => t('Cart'),
    'custom settings' => TRUE,
  );
}

/**
 * @param $ordered_subworks
 * @param $type_id
 * @param $subtype_id
 * @return mixed
 */
function bibdk_cart_ting_openformat_subwork_materialtype_actions($ordered_subworks, $type_id, $subtype_id) {
  $lookup_pids = array_keys($ordered_subworks[$type_id][$subtype_id]['manifest']['manifestations']);
  $link = bibdk_cart_get_link($lookup_pids);

  $render['cart'] = array(
    '#theme' => 'bibdk_cart_button_subwork',
    '#add_to_cart' => $link,
  );

  return $render;
}

/**
 * Implements hook_user_login. Check if user had elements in cart before login.
 * If elements are not on webservice - then add to webservice.
 *
 * @param $edit
 * @param $account
 */
function bibdk_cart_user_login(&$edit, $account) {
  if (ding_user_is_provider_user($account)) {
    $user_cart = _bibdk_cart_get_cart_on_webservice($account);
    if ($_SESSION['bibdk_cart']) {
      foreach ($_SESSION['bibdk_cart'] as $key => $element) {
        if (!in_array($key, $user_cart)) {
          $id = _bibdk_cart_add_content_webservice($element->toService());
          $element->setId($id);
          $_SESSION['bibdk_cart'][$key] = $element;
        }
      }
      $_SESSION['bibdk_cart'] += $user_cart;
    }
    else {
      $_SESSION['bibdk_cart'] = $user_cart;
    }
  }
}

/** Implements hook_bibdk_reservation_complete
 *
 * @param $pids
 * @param $order_result
 */
function bibdk_cart_bibdk_reservation_complete($pids, $order_result) {
  if ($element = BibdkCart::checkInCart($pids)) {
    $element->setStatus('reservation_complete');
    $element->save();
    drupal_add_js(drupal_get_path('module', 'bibdk_cart') . '/js/bibdk_cart_reload.js');
  }
}


function bibdk_cart_reservation_update_status($status, $pids) {
  $ids = explode(';', $pids);
  foreach ($ids as $id) {
    if ($element = BibdkCart::checkInCart($id)) {
      $element->setStatus($status);
      $element->save();

    }
  }
  drupal_add_js(drupal_get_path('module', 'bibdk_cart') . '/js/bibdk_cart_reload.js');
}

/**
 * Hack to remove html tags from fields
 *
 * @param $view
 */
function _bibdk_cart_manifestation_view_strip_links(&$view) {
  if (isset($view['#fields']) && is_array($view['#fields'])) {
    foreach ($view['#fields'] as $key => $field) {
      if (isset($field[0]['#markup'])) {
        $view['#fields'][$key][0]['#markup'] = strip_tags($field[0]['#markup']);
      }
    }
  }
}
